'use client';

import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  FileText, 
  CheckCircle2, 
  Circle, 
  AlertTriangle, 
  Calendar, 
  Clock,
  Star,
  Tag,
  TrendingUp,
  Target,
  BarChart3,
  Copy,
  Check,
  ZoomIn,
  ZoomOut,
  Bot,
  Download,
  History,
  Plus,
  Edit,
  Trash2,
  X
} from 'lucide-react';
import type { Task } from '@/lib/types';
import { format, isToday, isTomorrow, isPast, isThisWeek, isThisMonth, formatDistanceToNow } from 'date-fns';
import { toast } from '@/hooks/use-toast';
import { getUserTaskActivityLog, type TaskActivity } from '@/lib/firebase-task-activity';
import { useAuth } from '@/context/auth-context';

interface TaskSummaryDialogProps {
  tasks: Task[];
  onAskAI?: () => void;
}

export function TaskSummaryDialog({ tasks, onAskAI }: TaskSummaryDialogProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [zoomLevel, setZoomLevel] = useState(100);
  const [activityLog, setActivityLog] = useState<TaskActivity[]>([]);
  const [loadingActivity, setLoadingActivity] = useState(false);
  const { user } = useAuth();

  // Load activity log when dialog opens
  useEffect(() => {
    if (isOpen && user) {
      setLoadingActivity(true);
      getUserTaskActivityLog(user.uid, 100)
        .then(setActivityLog)
        .catch(err => {
          console.error('Failed to load activity log:', err);
          setActivityLog([]);
        })
        .finally(() => setLoadingActivity(false));
    }
  }, [isOpen, user]);

  // Copy to clipboard function
  const copyToClipboard = async (text: string, taskId: string, label: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(taskId);
      toast({
        title: "Copied!",
        description: `${label} copied to clipboard`,
      });
      setTimeout(() => setCopiedId(null), 2000);
    } catch (error) {
      toast({
        title: "Failed to copy",
        description: "Could not copy to clipboard",
        variant: "destructive",
      });
    }
  };

  // Copy all tasks function
  const copyAllTasks = () => {
    const allTasksText = [
      '📊 TASK SUMMARY & OVERVIEW',
      '=' .repeat(50),
      '',
      '📈 STATISTICS:',
      `Total Tasks: ${stats.total}`,
      `Completed: ${stats.completed} (${completionRate}%)`,
      `Active: ${stats.active}`,
      `Overdue: ${stats.overdue}`,
      `Due Today: ${stats.dueToday}`,
      `Due Tomorrow: ${stats.dueTomorrow}`,
      `Starred: ${stats.starred}`,
      '',
      '🏷️ POPULAR TAGS:',
      tagCounts.slice(0, 10).map(({ tag, count }) => `  • ${tag} (${count})`).join('\n'),
      '',
      '📋 ALL TASKS:',
      '=' .repeat(50),
      '',
    ];

    // Add tasks by category
    const categories = [
      { title: '⚠️ OVERDUE', tasks: tasksByStatus.overdue },
      { title: '🕐 DUE TODAY', tasks: tasksByStatus.dueToday },
      { title: '📅 DUE TOMORROW', tasks: tasksByStatus.dueTomorrow },
      { title: '📈 UPCOMING', tasks: tasksByStatus.upcoming },
      { title: '⭕ NO DUE DATE', tasks: tasksByStatus.noDueDate },
      { title: '✅ COMPLETED', tasks: tasksByStatus.completed },
    ];

    categories.forEach(({ title, tasks: categoryTasks }) => {
      if (categoryTasks.length > 0) {
        allTasksText.push('');
        allTasksText.push(title);
        allTasksText.push('-'.repeat(50));
        categoryTasks.forEach((task, idx) => {
          allTasksText.push(`${idx + 1}. ${task.text}`);
          if (task.description) {
            allTasksText.push(`   Description: ${task.description}`);
          }
          if (task.tags && task.tags.length > 0) {
            allTasksText.push(`   Tags: ${task.tags.join(', ')}`);
          }
          if (task.dueDate) {
            allTasksText.push(`   Due: ${formatDate(task.dueDate)}`);
          }
          if (task.starred) {
            allTasksText.push(`   ⭐ Starred`);
          }
          allTasksText.push('');
        });
      }
    });

    allTasksText.push('');
    allTasksText.push('Generated by Lunchbox AI Task Manager');
    allTasksText.push(`Date: ${new Date().toLocaleString()}`);

    copyToClipboard(allTasksText.join('\n'), 'all-tasks', 'All tasks');
  };

  // Generate AI summary prompt
  const handleAskAI = () => {
    if (onAskAI) {
      setIsOpen(false);
      onAskAI();
    }
  };

  // Zoom functions
  const zoomIn = () => setZoomLevel(prev => Math.min(prev + 10, 200));
  const zoomOut = () => setZoomLevel(prev => Math.max(prev - 10, 50));
  const resetZoom = () => setZoomLevel(100);

  // Calculate statistics
  const stats = {
    total: tasks.length,
    completed: tasks.filter(t => t.completed).length,
    active: tasks.filter(t => !t.completed).length,
    overdue: tasks.filter(t => t.dueDate && isPast(new Date(t.dueDate)) && !t.completed).length,
    dueToday: tasks.filter(t => t.dueDate && isToday(new Date(t.dueDate)) && !t.completed).length,
    dueTomorrow: tasks.filter(t => t.dueDate && isTomorrow(new Date(t.dueDate)) && !t.completed).length,
    dueThisWeek: tasks.filter(t => t.dueDate && isThisWeek(new Date(t.dueDate)) && !t.completed).length,
    dueThisMonth: tasks.filter(t => t.dueDate && isThisMonth(new Date(t.dueDate)) && !t.completed).length,
    starred: tasks.filter(t => t.starred).length,
    withTags: tasks.filter(t => t.tags && t.tags.length > 0).length,
    noDueDate: tasks.filter(t => !t.dueDate && !t.completed).length,
  };

  // Calculate completion rate
  const completionRate = stats.total > 0 ? Math.round((stats.completed / stats.total) * 100) : 0;

  // Group tasks by status
  const tasksByStatus = {
    overdue: tasks.filter(t => t.dueDate && isPast(new Date(t.dueDate)) && !t.completed),
    dueToday: tasks.filter(t => t.dueDate && isToday(new Date(t.dueDate)) && !t.completed),
    dueTomorrow: tasks.filter(t => t.dueDate && isTomorrow(new Date(t.dueDate)) && !t.completed),
    upcoming: tasks.filter(t => t.dueDate && !isPast(new Date(t.dueDate)) && !isToday(new Date(t.dueDate)) && !isTomorrow(new Date(t.dueDate)) && !t.completed),
    noDueDate: tasks.filter(t => !t.dueDate && !t.completed),
    completed: tasks.filter(t => t.completed),
  };

  // Get all unique tags
  const allTags = Array.from(new Set(tasks.flatMap(t => t.tags || [])));
  const tagCounts = allTags.map(tag => ({
    tag,
    count: tasks.filter(t => t.tags?.includes(tag)).length
  })).sort((a, b) => b.count - a.count);

  const formatDate = (dateString: string) => {
    try {
      return format(new Date(dateString), 'MMM d, yyyy');
    } catch {
      return 'Invalid date';
    }
  };

  const TaskList = ({ tasks: taskList, title, icon: Icon, emptyMessage }: { 
    tasks: Task[]; 
    title: string; 
    icon: any; 
    emptyMessage: string;
  }) => (
    <div className="space-y-2">
      <div className="flex items-center gap-2 mb-3">
        <Icon className="h-4 w-4 text-gray-400" />
        <h3 className="text-sm font-semibold text-white">{title}</h3>
        <Badge variant="secondary" className="text-xs bg-gray-800 text-gray-300">
          {taskList.length}
        </Badge>
      </div>
      {taskList.length === 0 ? (
        <p className="text-xs text-gray-500 pl-6">{emptyMessage}</p>
      ) : (
        <div className="space-y-1.5 pl-6">
          {taskList.map(task => (
            <div key={task.id} className="group flex items-start gap-2 p-2 rounded-lg bg-gray-800/30 hover:bg-gray-800/50 transition-colors relative">
              <div className="shrink-0 mt-0.5">
                {task.completed ? (
                  <CheckCircle2 className="h-4 w-4 text-green-500" />
                ) : (
                  <Circle className="h-4 w-4 text-gray-500" />
                )}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <p 
                    className={`text-sm select-text cursor-text ${task.completed ? 'line-through text-gray-500' : 'text-gray-200'}`}
                    title="Click to select and copy"
                  >
                    {task.text}
                  </p>
                  {task.starred && (
                    <Star className="h-3 w-3 fill-yellow-400 text-yellow-400 shrink-0" />
                  )}
                </div>
                {task.description && (
                  <p className="text-xs text-gray-400 mt-1 select-text cursor-text" title="Click to select and copy">
                    {task.description}
                  </p>
                )}
                <div className="flex items-center gap-2 mt-1 flex-wrap">
                  {task.dueDate && (
                    <span className={`text-xs flex items-center gap-1 select-text cursor-text ${
                      isPast(new Date(task.dueDate)) && !task.completed
                        ? 'text-red-400'
                        : 'text-gray-400'
                    }`}>
                      <Calendar className="h-3 w-3" />
                      {formatDate(task.dueDate)}
                    </span>
                  )}
                  {task.tags && task.tags.length > 0 && (
                    <div className="flex items-center gap-1 flex-wrap">
                      {task.tags.map((tag, idx) => (
                        <Badge 
                          key={idx} 
                          variant="secondary" 
                          className="text-[10px] bg-blue-500/20 text-blue-300 border border-blue-500/30 px-1.5 py-0 select-text cursor-text"
                          title="Click to select and copy"
                        >
                          {tag}
                        </Badge>
                      ))}
                    </div>
                  )}
                </div>
              </div>
              {/* Copy Button */}
              <Button
                variant="ghost"
                size="sm"
                className="absolute top-2 right-2 h-6 w-6 p-0 opacity-0 group-hover:opacity-100 transition-opacity"
                onClick={() => {
                  const copyText = [
                    task.text,
                    task.description,
                    task.tags?.length ? `Tags: ${task.tags.join(', ')}` : '',
                    task.dueDate ? `Due: ${formatDate(task.dueDate)}` : ''
                  ].filter(Boolean).join('\n');
                  copyToClipboard(copyText, task.id, 'Task details');
                }}
                title="Copy task details"
              >
                {copiedId === task.id ? (
                  <Check className="h-3 w-3 text-green-400" />
                ) : (
                  <Copy className="h-3 w-3 text-gray-400" />
                )}
              </Button>
            </div>
          ))}
        </div>
      )}
    </div>
  );

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button 
          variant="outline" 
          size="sm"
          className="bg-gray-800 border-gray-700 hover:bg-gray-700 text-gray-300 hover:text-white"
        >
          <FileText className="h-4 w-4 mr-2" />
          Task Summary
        </Button>
      </DialogTrigger>
      <DialogContent className="bg-gray-900 border-gray-700 max-w-4xl max-h-[90vh] flex flex-col p-0">
        <DialogHeader className="px-6 pt-6 pb-4 border-b border-gray-700">
          <div className="flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <DialogTitle className="text-white flex items-center gap-2">
                <BarChart3 className="h-5 w-5 text-blue-400" />
                Task Summary & Overview
              </DialogTitle>
              {/* Zoom Controls */}
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={zoomOut}
                  disabled={zoomLevel <= 50}
                  className="h-7 w-7 p-0 text-gray-400 hover:text-white disabled:opacity-30"
                  title="Zoom out (Min: 50%)"
                >
                  <ZoomOut className="h-4 w-4" />
                </Button>
                <button
                  onClick={resetZoom}
                  className="text-xs text-gray-400 hover:text-white min-w-[3rem] text-center font-medium hover:bg-gray-800 px-2 py-1 rounded transition-colors"
                  title="Reset zoom to 100%"
                >
                  {zoomLevel}%
                </button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={zoomIn}
                  disabled={zoomLevel >= 200}
                  className="h-7 w-7 p-0 text-gray-400 hover:text-white disabled:opacity-30"
                  title="Zoom in (Max: 200%)"
                >
                  <ZoomIn className="h-4 w-4" />
                </Button>
              </div>
            </div>
            {/* Action Buttons */}
            <div className="flex items-center gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={copyAllTasks}
                className="flex-1 bg-gray-800 border-gray-700 hover:bg-gray-700 text-gray-300 hover:text-white"
              >
                {copiedId === 'all-tasks' ? (
                  <>
                    <Check className="h-4 w-4 mr-2 text-green-400" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    Copy All Tasks
                  </>
                )}
              </Button>
              {onAskAI && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleAskAI}
                  className="flex-1 bg-gradient-to-r from-purple-600 to-blue-600 border-purple-500 hover:from-purple-700 hover:to-blue-700 text-white"
                >
                  <Bot className="h-4 w-4 mr-2" />
                  Ask AI About Tasks
                </Button>
              )}
            </div>
          </div>
        </DialogHeader>
        
        <div className="flex-1 overflow-y-auto px-6 py-4">
          <div className="space-y-6 pb-4" style={{ fontSize: `${zoomLevel}%` }}>
            {/* Statistics Overview */}
            <div className="space-y-3">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-blue-400" />
                Statistics
              </h3>
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
                <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-3">
                  <div className="text-2xl font-bold text-white">{stats.total}</div>
                  <div className="text-xs text-gray-400 mt-1">Total Tasks</div>
                </div>
                <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-3">
                  <div className="text-2xl font-bold text-green-400">{stats.completed}</div>
                  <div className="text-xs text-gray-400 mt-1">Completed</div>
                </div>
                <div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-3">
                  <div className="text-2xl font-bold text-blue-400">{stats.active}</div>
                  <div className="text-xs text-gray-400 mt-1">Active</div>
                </div>
                <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3">
                  <div className="text-2xl font-bold text-red-400">{stats.overdue}</div>
                  <div className="text-xs text-gray-400 mt-1">Overdue</div>
                </div>
                <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-3">
                  <div className="text-2xl font-bold text-yellow-400">{stats.dueToday}</div>
                  <div className="text-xs text-gray-400 mt-1">Due Today</div>
                </div>
                <div className="bg-orange-500/10 border border-orange-500/30 rounded-lg p-3">
                  <div className="text-2xl font-bold text-orange-400">{stats.dueTomorrow}</div>
                  <div className="text-xs text-gray-400 mt-1">Due Tomorrow</div>
                </div>
                <div className="bg-purple-500/10 border border-purple-500/30 rounded-lg p-3">
                  <div className="text-2xl font-bold text-purple-400">{stats.starred}</div>
                  <div className="text-xs text-gray-400 mt-1">Starred</div>
                </div>
                <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-3">
                  <div className="text-2xl font-bold text-white">{completionRate}%</div>
                  <div className="text-xs text-gray-400 mt-1">Completion Rate</div>
                </div>
              </div>
            </div>

            {/* Completion Progress Bar */}
            <div className="space-y-2">
              <div className="flex items-center justify-between text-xs text-gray-400">
                <span>Progress</span>
                <span>{stats.completed} / {stats.total} tasks</span>
              </div>
              <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-green-500 to-emerald-500 transition-all duration-500"
                  style={{ width: `${completionRate}%` }}
                />
              </div>
            </div>

            {/* Tags Overview */}
            {tagCounts.length > 0 && (
              <div className="space-y-3">
                <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                  <Tag className="h-4 w-4 text-blue-400" />
                  Popular Tags
                </h3>
                <div className="flex flex-wrap gap-2">
                  {tagCounts.slice(0, 10).map(({ tag, count }) => (
                    <button
                      key={tag}
                      onClick={() => copyToClipboard(tag, `tag-${tag}`, 'Tag')}
                      className="group relative"
                      title="Click to copy tag"
                    >
                      <Badge 
                        variant="secondary"
                        className="bg-blue-500/20 text-blue-300 border border-blue-500/30 hover:bg-blue-500/30 cursor-pointer select-text"
                      >
                        {tag} <span className="ml-1 text-blue-400">({count})</span>
                      </Badge>
                      {copiedId === `tag-${tag}` && (
                        <Check className="absolute -top-1 -right-1 h-3 w-3 text-green-400 bg-gray-900 rounded-full" />
                      )}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {/* Task Lists by Category */}
            <div className="space-y-6 border-t border-gray-700 pt-6">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <Target className="h-4 w-4 text-blue-400" />
                Tasks by Category
              </h3>

              {stats.overdue > 0 && (
                <TaskList
                  tasks={tasksByStatus.overdue}
                  title="Overdue"
                  icon={AlertTriangle}
                  emptyMessage="No overdue tasks"
                />
              )}

              {stats.dueToday > 0 && (
                <TaskList
                  tasks={tasksByStatus.dueToday}
                  title="Due Today"
                  icon={Clock}
                  emptyMessage="No tasks due today"
                />
              )}

              {stats.dueTomorrow > 0 && (
                <TaskList
                  tasks={tasksByStatus.dueTomorrow}
                  title="Due Tomorrow"
                  icon={Calendar}
                  emptyMessage="No tasks due tomorrow"
                />
              )}

              <TaskList
                tasks={tasksByStatus.upcoming}
                title="Upcoming"
                icon={TrendingUp}
                emptyMessage="No upcoming tasks"
              />

              {stats.noDueDate > 0 && (
                <TaskList
                  tasks={tasksByStatus.noDueDate}
                  title="No Due Date"
                  icon={Circle}
                  emptyMessage="All tasks have due dates"
                />
              )}

              <TaskList
                tasks={tasksByStatus.completed}
                title="Completed"
                icon={CheckCircle2}
                emptyMessage="No completed tasks yet"
              />
            </div>

            {/* Activity Log */}
            <div className="space-y-3 border-t border-gray-700 pt-6">
              <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                <History className="h-4 w-4 text-blue-400" />
                Activity Log
              </h3>
              {loadingActivity ? (
                <p className="text-xs text-gray-500 pl-6">Loading activity...</p>
              ) : activityLog.length === 0 ? (
                <p className="text-xs text-gray-500 pl-6">No activity yet</p>
              ) : (
                <div className="space-y-1.5 pl-6">
                  {activityLog.slice(0, 50).map((activity, idx) => {
                    const task = tasks.find(t => t.id === activity.taskId);
                    const taskName = task?.text || 'Unknown task';
                    const timeAgo = formatDistanceToNow(new Date(activity.timestamp), { addSuffix: true });
                    
                    const getActivityIcon = () => {
                      switch (activity.activityType) {
                        case 'created': return <Plus className="h-3 w-3 text-green-400" />;
                        case 'completed': return <CheckCircle2 className="h-3 w-3 text-green-400" />;
                        case 'uncompleted': return <Circle className="h-3 w-3 text-gray-400" />;
                        case 'edited': return <Edit className="h-3 w-3 text-blue-400" />;
                        case 'deleted': return <Trash2 className="h-3 w-3 text-red-400" />;
                        case 'starred': return <Star className="h-3 w-3 text-yellow-400 fill-yellow-400" />;
                        case 'unstarred': return <Star className="h-3 w-3 text-gray-400" />;
                        default: return <Circle className="h-3 w-3 text-gray-400" />;
                      }
                    };

                    const getActivityText = () => {
                      switch (activity.activityType) {
                        case 'created': return 'Created';
                        case 'completed': return 'Completed';
                        case 'uncompleted': return 'Uncompleted';
                        case 'edited': return 'Edited';
                        case 'deleted': return 'Deleted';
                        case 'starred': return 'Starred';
                        case 'unstarred': return 'Unstarred';
                        case 'repeating_scheduled': return 'Scheduled repeating';
                        case 'repeating_updated': return 'Updated repeating';
                        default: return activity.activityType;
                      }
                    };

                    return (
                      <div 
                        key={activity.id || idx} 
                        className="flex items-start gap-2 py-1.5 px-2 rounded text-xs text-gray-300 hover:bg-gray-800/30 transition-colors"
                      >
                        <div className="shrink-0 mt-0.5">
                          {getActivityIcon()}
                        </div>
                        <div className="flex-1 min-w-0">
                          <span className="text-gray-400">{getActivityText()}</span>
                          <span className="text-gray-500 mx-1">•</span>
                          <span className="text-gray-300 truncate" title={taskName}>
                            {taskName}
                          </span>
                          {activity.details?.description && (
                            <span className="text-gray-500 ml-1">• {activity.details.description}</span>
                          )}
                        </div>
                        <span className="text-gray-500 shrink-0 text-[10px]">{timeAgo}</span>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

